//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMAkademik.Models.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AkademikEntities : DbContext
    {
        public AkademikEntities()
            : base("name=AkademikEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ms_agama> ms_agama { get; set; }
        public virtual DbSet<ms_desa> ms_desa { get; set; }
        public virtual DbSet<ms_fakultas> ms_fakultas { get; set; }
        public virtual DbSet<ms_jenjang_pendidikan> ms_jenjang_pendidikan { get; set; }
        public virtual DbSet<ms_jurusan> ms_jurusan { get; set; }
        public virtual DbSet<ms_kabupaten> ms_kabupaten { get; set; }
        public virtual DbSet<ms_kecamatan> ms_kecamatan { get; set; }
        public virtual DbSet<ms_mahasiswa> ms_mahasiswa { get; set; }
        public virtual DbSet<ms_provinsi> ms_provinsi { get; set; }
    }
}
