//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMAkademik.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ms_jenjang_pendidikan
    {
        public string kode_jenjang_pendidikan { get; set; }
        public string nama_jenjang_pendidikan { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public string updated_by { get; set; }
        public Nullable<bool> is_active { get; set; }
    }
}
