//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMAkademik.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ms_mahasiswa
    {
        public string nim { get; set; }
        public string nama_lengkap { get; set; }
        public string nama_panggilan { get; set; }
        public string tempat_lahir { get; set; }
        public Nullable<System.DateTime> tanggal_Lahir { get; set; }
        public string kode_agama { get; set; }
        public Nullable<bool> jenis_kelamin { get; set; }
        public string kode_sipil { get; set; }
        public string kode_warganegara { get; set; }
        public string handphone { get; set; }
        public string email { get; set; }
        public string alamat { get; set; }
        public string rt { get; set; }
        public string rw { get; set; }
        public string kode_kota { get; set; }
        public string kode_provinsi { get; set; }
        public string kode_pos { get; set; }
        public string kode_negara { get; set; }
    }
}
