//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMAkademik.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLM_MATAKULIAH
    {
        public string KODEMTK { get; set; }
        public string KODEJURUSAN { get; set; }
        public string KODEKMTK { get; set; }
        public string NAMAMTK { get; set; }
        public Nullable<int> SEMESTER { get; set; }
        public Nullable<int> SKS { get; set; }
        public Nullable<int> T { get; set; }
        public Nullable<int> P { get; set; }
        public Nullable<int> K { get; set; }
    
        public virtual TBLM_JURUSAN TBLM_JURUSAN { get; set; }
        public virtual TBLM_KMTK TBLM_KMTK { get; set; }
    }
}
