//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMAkademik.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLM_MAHASISWA
    {
        public string NIM { get; set; }
        public long NIK { get; set; }
        public string NOPENDAFTARAN { get; set; }
        public int IDSTATUSMAHASISWA { get; set; }
        public int IDPROGRAM { get; set; }
        public string NAMALENGKAP { get; set; }
        public string NAMAPANGGILAN { get; set; }
        public string TEMPATLAHIR { get; set; }
        public System.DateTime TANGGALLAHIR { get; set; }
        public int IDAGAMA { get; set; }
        public int IDSEX { get; set; }
        public int IDSTATUSSIPIL { get; set; }
        public int IDWARGANEGARA { get; set; }
        public string HP { get; set; }
        public string EMAIL { get; set; }
        public string TELEPON { get; set; }
        public string ALAMAT { get; set; }
        public string RT { get; set; }
        public string RW { get; set; }
        public Nullable<int> IDDESA { get; set; }
        public Nullable<int> IDNEGARA { get; set; }
        public string SD { get; set; }
        public Nullable<System.DateTime> TGLSSTBSD { get; set; }
        public Nullable<int> THNMASUKSD { get; set; }
        public Nullable<int> THNKELUARSD { get; set; }
        public string SMP { get; set; }
        public Nullable<System.DateTime> TLGSSTBSMP { get; set; }
        public Nullable<int> THNMASUKSMP { get; set; }
        public Nullable<int> THNKELUARSMP { get; set; }
        public string SMA { get; set; }
        public Nullable<System.DateTime> TGLSSTBSMA { get; set; }
        public Nullable<int> THNMASUKSMA { get; set; }
        public Nullable<int> THNKELUARSMA { get; set; }
        public string JURUSANSMA { get; set; }
        public string NAMAYAH { get; set; }
        public string TEMPATLAHIRAYAH { get; set; }
        public Nullable<System.DateTime> TANGGALLAHIRAYAH { get; set; }
        public string ALAMATAYAH { get; set; }
        public string PEKERJAANAYAH { get; set; }
        public string NAMAIBU { get; set; }
        public string TEMPATLAHIRIBU { get; set; }
        public Nullable<System.DateTime> TANGGALLAHIRIBU { get; set; }
        public string ALAMATIBU { get; set; }
        public string FILENAME { get; set; }
        public string CONTENTTYPE { get; set; }
        public byte[] DATA { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDDATE { get; set; }
        public string UPDATEDBY { get; set; }
    
        public virtual TBLM_AGAMA TBLM_AGAMA { get; set; }
        public virtual TBLM_DESA TBLM_DESA { get; set; }
        public virtual TBLM_NEGARA TBLM_NEGARA { get; set; }
        public virtual TBLM_PROGRAM TBLM_PROGRAM { get; set; }
        public virtual TBLM_SATUSMAHASISWA TBLM_SATUSMAHASISWA { get; set; }
        public virtual TBLM_SEX TBLM_SEX { get; set; }
        public virtual TBLM_STATUSSIPIL TBLM_STATUSSIPIL { get; set; }
        public virtual TBLM_WARGANEGARA TBLM_WARGANEGARA { get; set; }
    }
}
