//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMAkademik.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLM_KOTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLM_KOTA()
        {
            this.TBLM_KECAMATAN = new HashSet<TBLM_KECAMATAN>();
        }
    
        public int IDKOTA { get; set; }
        public Nullable<int> IDPROVINSI { get; set; }
        public string NAMA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLM_KECAMATAN> TBLM_KECAMATAN { get; set; }
        public virtual TBLM_PROVINSI TBLM_PROVINSI { get; set; }
    }
}
