//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMAkademik.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLM_KMTK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLM_KMTK()
        {
            this.TBLM_MATAKULIAH = new HashSet<TBLM_MATAKULIAH>();
        }
    
        public string KODEKMTK { get; set; }
        public string NAMA { get; set; }
        public Nullable<bool> AKTIF { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLM_MATAKULIAH> TBLM_MATAKULIAH { get; set; }
    }
}
