//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMAkademik.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLM_DOSEN
    {
        public int IDDOSEN { get; set; }
        public Nullable<int> NIP { get; set; }
        public Nullable<int> NUPTK { get; set; }
        public string NAMALENGKAP { get; set; }
        public string NAMAPANGGILAN { get; set; }
        public string TEMPATLAHIR { get; set; }
        public Nullable<System.DateTime> TANGGALLAHIR { get; set; }
        public string ALAMAT { get; set; }
        public string EMAIL { get; set; }
        public string HP { get; set; }
        public string TELEPON { get; set; }
        public Nullable<int> IDAGAMA { get; set; }
        public Nullable<int> IDSEX { get; set; }
        public string FILENAME { get; set; }
        public string CONTENTTYPE { get; set; }
        public byte[] DATA { get; set; }
    
        public virtual TBLM_AGAMA TBLM_AGAMA { get; set; }
        public virtual TBLM_SEX TBLM_SEX { get; set; }
    }
}
